#!/usr/bin/env python3
"""Assemble ``{teamname}-audit-materials.zip`` in the layout the Data Integrity Policy asks for.

    task3/
    ├── code/            this repository's training + inference code, README.md, requirements.txt
    ├── data-split.md    generated by the export stage of train_task3_audit.py
    ├── submission_record.md
    └── logs/            audit-logs/, console-logs/, runs/<experiment>/{config.*, logs/}, export/

Code comes from the checkout this script lives in; logs from ``--logs-dir`` (the Drive folder
train_task3_audit.py mirrored into). Nothing under ``logs/`` is altered: files are copied
byte for byte, the audit tools' ``.log`` / ``.log.csv`` names included.

    python audit/make_audit_package.py --logs-dir /content/drive/MyDrive/mrixfields2026/docker_final_logs \\
        --out /content/drive/MyDrive/mrixfields2026/inzva_mri-audit-materials.zip

Checkpoints (~110 MB each, model + optimizer) are left out unless ``--with-checkpoints`` is
given, because the policy caps the package at 10 GB; the weights-only final model in
``logs/export/`` and the sha256 list of every checkpoint are always included.
"""

from __future__ import annotations

import argparse
import fnmatch
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: (source relative to the repo, destination relative to task3/code/, glob patterns kept)
CODE = [
    ("mrixfields", "mrixfields", ["*.py"]),
    ("experiment-pipeline/eval_pipeline", "experiment-pipeline/eval_pipeline", ["*.py"]),
    ("experiment-pipeline/components", "experiment-pipeline/components", ["*.py"]),
    ("experiment-pipeline/configs", "experiment-pipeline/configs", ["task3_*.toml"]),
    ("experiment-pipeline/tests", "experiment-pipeline/tests", ["*.py"]),
    ("experiment-pipeline/scripts", "experiment-pipeline/scripts", ["*.py"]),
    ("scripts", "scripts", ["*.py"]),
    ("tests", "tests", ["*.py"]),
]
CODE_FILES = [
    ("experiment-pipeline/audit_monitor.py", "experiment-pipeline/audit_monitor.py"),
    ("experiment-pipeline/audit_utils.py", "experiment-pipeline/audit_utils.py"),
    ("experiment-pipeline/audit_dataset.py", "experiment-pipeline/audit_dataset.py"),
    ("experiment-pipeline/audit_mirror.py", "experiment-pipeline/audit_mirror.py"),
    ("experiment-pipeline/train_task3_audit.py", "experiment-pipeline/train_task3_audit.py"),
    ("experiment-pipeline/main.py", "experiment-pipeline/main.py"),
    ("experiment-pipeline/pyproject.toml", "experiment-pipeline/pyproject.toml"),
    ("experiment-pipeline/README.md", "experiment-pipeline/README.md"),
    ("setup.py", "setup.py"),
    ("README.md", "REPO_README.md"),
    ("docs/metric_formulas.md", "docs/metric_formulas.md"),
    ("audit/README.md", "README.md"),
    ("audit/requirements.txt", "requirements.txt"),
    ("audit/task3_audit_colab.ipynb", "task3_audit_colab.ipynb"),
    ("audit/submission_record.md", "submission_record.md"),
    ("audit/make_audit_package.py", "audit/make_audit_package.py"),
]
#: Under --logs-dir: (subdirectory, patterns kept, always?)
LOGS = [
    ("audit-logs", ["*"], True),
    ("console-logs", ["*"], True),
    ("export", ["*"], True),
    ("runs", ["config.source.toml", "config.resolved.json", "*.jsonl", "*.json", "*.md",
              "*.sha256", "*.txt"], True),
    ("runs/export", ["*"], True),      # weights-only final model, checksums, data-split.md
    ("runs", ["*.pt"], False),
    # runs/submission_reproduced/task3.zip (1.3 GB) is deliberately left out: it is the
    # leaderboard submission itself, recorded by ID in submission_record.md.
]
SECRET_KEYS = {"PERSONAL_ACCESS_TOKEN", "SYNAPSE_AUTH_TOKEN", "AUTH_TOKEN", "GITHUB_TOKEN"}
TEXT_SUFFIXES = {".py", ".toml", ".md", ".txt", ".json", ".jsonl", ".ipynb"}


def matches(path: Path, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(path.name, p) for p in patterns)


def walk(base: Path, patterns: list[str]):
    for path in sorted(base.rglob("*")):
        if not path.is_file() or "__pycache__" in path.parts or path.name.startswith("."):
            continue
        if matches(path, patterns):
            yield path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--logs-dir", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    parser.add_argument("--team", default="inzva_mri")
    parser.add_argument("--with-checkpoints", action="store_true",
                        help="include runs/*/artifacts/*.pt (model + optimizer, ~110 MB each)")
    parser.add_argument("--docker-dir", type=Path, default=None,
                        help="a pulled/extracted container app/ holding weights/task3.pt (default: "
                             "the first of <logs-dir>/docker_submission/app, <repo>/docker_submission/app, "
                             "<repo>/../task3_extracted/app that exists)")
    args = parser.parse_args()

    # The container's code is tracked under audit/docker (no weights). The shipped weights
    # come from wherever the image was pulled or extracted to, if anywhere.
    docker_code = ROOT / "audit" / "docker"
    shipped = next((p / "weights" / "task3.pt" for p in (
        [args.docker_dir] if args.docker_dir else
        [args.logs_dir / "docker_submission" / "app", ROOT / "docker_submission" / "app",
         ROOT.parent / "task3_extracted" / "app"]) if (p / "weights" / "task3.pt").is_file()), None)
    entries: list[tuple[Path, str]] = []

    for source, destination, patterns in CODE:
        base = ROOT / source
        if not base.is_dir():
            print(f"skip (missing): {source}", file=sys.stderr)
            continue
        for path in walk(base, patterns):
            entries.append((path, f"task3/code/{destination}/{path.relative_to(base).as_posix()}"))
    for source, destination in CODE_FILES:
        path = ROOT / source
        if path.is_file():
            entries.append((path, f"task3/code/{destination}"))
        else:
            print(f"skip (missing): {source}", file=sys.stderr)
    for path in walk(docker_code, ["*"]):
        entries.append((path, f"task3/code/docker/{path.relative_to(docker_code).as_posix()}"))
    if shipped is not None:
        entries.append((shipped, "task3/code/docker/app/weights/task3.pt"))
    else:
        print("note: shipped task3.pt not found; the container code goes in without its weights "
              "(see the notebook's optional pull cell, or pass --docker-dir)", file=sys.stderr)

    split = args.logs_dir / "export" / "data-split.md"
    if split.is_file():
        entries.append((split, "task3/data-split.md"))
    else:
        print(f"WARNING: {split} missing -- run the export stage first", file=sys.stderr)
    entries.append((ROOT / "audit" / "submission_record.md", "task3/submission_record.md"))

    for sub, patterns, always in LOGS:
        if not always and not args.with_checkpoints:
            continue
        base = args.logs_dir / sub
        if not base.is_dir():
            print(f"skip (missing): logs/{sub}", file=sys.stderr)
            continue
        for path in walk(base, patterns):
            entries.append((path, f"task3/logs/{sub}/{path.relative_to(base).as_posix()}"))

    # Nothing secret may ship: the .env is never copied, but text files are checked anyway.
    for path, _ in entries:
        if path.suffix not in TEXT_SUFFIXES:
            continue
        for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
            if line.startswith("-----BEGIN") and "PRIVATE KEY" in line:
                raise SystemExit(f"refusing to package {path}: private key material")
            key, sep, value = line.strip().partition("=")
            if sep and key.strip() in SECRET_KEYS and value.strip(" '\"") not in ("", "<redacted>"):
                raise SystemExit(f"refusing to package {path}: sets {key.strip()}")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    total = 0
    seen: set[str] = set()
    with zipfile.ZipFile(args.out, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=6) as archive:
        for path, name in entries:
            if name in seen:
                continue
            seen.add(name)
            archive.write(path, name)
            total += path.stat().st_size
    size = args.out.stat().st_size
    print(f"{len(seen)} files, {total / 1e9:.2f} GB uncompressed -> {args.out} ({size / 1e9:.2f} GB)")
    if size > 10e9:
        print("WARNING: over the 10 GB limit; drop --with-checkpoints or trim logs/runs", file=sys.stderr)
    expected = f"{args.team}-audit-materials.zip"
    if args.out.name != expected:
        print(f"note: the policy names the file {expected}", file=sys.stderr)


if __name__ == "__main__":
    main()
